services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"   # FastAPI のデフォルト
    depends_on:
      db:
        condition: service_healthy
    environment:
      # TODO: パスワード / ドライバ名などは必要に応じて調整
      - DATABASE_URL=mssql+pymssql://sa:YourStrong!Passw0rd@db:1433/dev
    volumes:
      - ./backend:/app:delegated

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: YourStrong!Passw0rd
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"YourStrong!Passw0rd\" -C -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - db_data:/var/opt/mssql

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000" # Next.js のデフォルト
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend:delegated
    command: npm run dev

volumes:
  db_data:
