services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"   # FastAPI のデフォルト
    depends_on:
      - db
    environment:
      # TODO: ユーザ・パスワードなどを変更
      - DATABASE_URL=postgresql://user:password@db:5432/dev
    volumes:
      - ./backend:/app:delegated

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      # TODO: ユーザ・パスワードなどを変更
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000" # Next.js のデフォルト
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend:delegated
    command: npm run dev

volumes:
  db_data:
