[project]
name = "keijiban"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "pyodbc>=5.2.0",
    "streamlit>=1.47.1",
]
